exp_name: UNet_iter_debug
timestamp_enabled: False
save_path: ./checkpoints


model_settings:
    type: unet
    in_channels: 3
    out_channels: 3
    width: 32
    block_size: 2
    compactor: False

train_settings:
    gpu: 0
    seed: 13
    grad_clip: 5
    trainer_type: iter
    resume: 

    optim:
        type: AdamW
        lr: !!float 1e-3
        weight_decay: 0.
        betas: [0.9, 0.9]
    
    scheduler:
        type: CosineAnnealingLR
        T_max: 200000
        eta_min: !!float 1e-7

    train_len: 200000
    warmup_len: -1
    save_ckpt_freq: !!float 5e3 

    loss:
        type: PSNRLoss
        loss_weight: 1
        reduction: mean

    datasets:
        train:
            # data type and root
            name: SIDD
            type: PairedImageDataset

            io_backend: 
                type: lmdb
            filename_tmpl: '{}'
 
            lq_path: ../feed/SIDD/train/input_crops.lmdb
            gt_path: ../feed/SIDD/train/gt_crops.lmdb

            # data preprocess
            gt_size: 256
            use_flip: false
            use_rot:  false

            # dataloader
            use_shuffle: True
            num_worker_per_gpu: 0
            batch_size_per_gpu: 1
            dataset_enlarge_ratio: 1
            prefetch_mode: ~ 

        val:
            name: SIDD_val
            type: PairedImageDataset
            io_backend: 
                type: lmdb
            lq_path: ../feed/SIDD/val/input_crops.lmdb
            gt_path: ../feed/SIDD/val/gt_crops.lmdb

        test:
            name: SIDD_val
            type: PairedImageDataset
            io_backend: 
                type: lmdb
            lq_path: ../feed/SIDD/val/input_crops.lmdb
            gt_path: ../feed/SIDD/val/gt_crops.lmdb

display:
    print_freq: 10



