model_settings:
    in_channels: 3
    out_channels: 3
    width: 32
    encoder_block: [2, 2, 4, 8]
    decoder_block: [2, 2, 2, 2]
    middle_block: 12
    res_connect: skip
    long_connect: cat
    head: True


training_settings:
    seed: 54
    epochs: 200
    batch_size: 14
    patch_size: 256
    workers: 6
    init_lr: 1.e-4
    lr_schedule:
        100: 1.e-4
        160: 5.e-5
        180: 2.5e-5
        -1: 1.e-5
    grad_clip: 5
