model_settings:
    in_channels: 3
    out_channels: 3
    width: 32
    block_size: 4
    res_connect: conv
    head: True

training_settings:
    seed: 54
    epochs: 80
    gpu: 7
    batch_size: 32
    patch_size: 256
    workers: 6
    init_lr: 1.e-4
    lr_schedule:
        20: 1.e-4
        40: 5.e-5
        60: 2.5e-5
        -1: 1.e-5
    grad_clip: 5
