model_settings:
    in_channels: 4
    out_channels: 
    init_channels: 8
    block_size: 2
    compactor: False

training_settings:
    seed: 54
    epochs: 80
    batch_size: 1
    patch_size: 512
    workers: 6
    init_lr: 1.e-4
    lr_schedule:
        40: 1.e-4
        # 40: 5.e-5
        # 60: 2.5e-5
        -1: 1.e-5
    grad_clip: 5
