model_settings:
    in_channels: 3
    out_channels: 3
    width: 32
    block_size: 4
    res_connect: conv
    head: True

training_settings:
    seed: 54
    epochs: 3000
    gpu: 4
    batch_size: 16
    patch_size: 256
    workers: 6
    init_lr: 2.e-4
    lr_schedule:
        0: 2.e-4
        # 160: 5.e-5
        # 180: 2.5e-5
        -1: 1.e-6
    grad_clip: 5
