model_settings:
    in_channels: 3
    out_channels: 3
    init_channels: 32
    block_size: 2
    compactor: False

training_settings:
    gpu: 1
    seed: 13
    epochs: 40
    batch_size: 32
    patch_size: 256
    workers: 4
    init_lr: 1.e-4
    lr_schedule:
        10: 1.e-4
        20: 5.e-5
        30: 2.5e-5
        -1: 1.e-5
    grad_clip: 5
