model_settings:
    BN: False
    bias: True
    act_func: relu
    in_channels: 3
    out_channels: 3
    init_channels: 64
    num_resblocks: 6
    num_memblocks: 6
    multi_supervised: False

training_settings:
    seed: 98
    epochs: 80
    batch_size: 8
    patch_size: 256
    workers: 4
    init_lr: 1.e-4
    lr_schedule:
        40: 1.e-4
        60: 5.e-5
        -1: 1.e-5
    grad_clip: 5
